#css 配置
cssConfig: &cssConfig
  extract: true
  # 开启 CSS source maps?
  sourceMap: false
  # css预设器配置项
  loaderOptions: {}
  # 启用 CSS modules for all css / pre-processor files.
  modules: false

#开发环境部署
devServeConfig: &devServeConfig
  host: 0.0.0.0
  port: 8080 # 要转发服务端口号
  https: false # 是否开启https
  open: true #配置自动启动浏览器  http:#172.11.11.22:8888/rest/XX/
  hotOnly: true # 热更新
#  proxy: http://zuul.router.com:8081   # 配置转发请求服务器件
  disableHostCheck: true

#多页面配置
pages: &pages
  index:
    entry: './src/pages/home/home.js'
    template: 'public/index.html'
    filename: 'index.html'
    title: 'index page'
    chunks: ['chunk-vendors', 'chunk-common', 'index']
  graph:
    entry: './src/pages/graph/graph.js'
    template: 'public/graph.html'
    filename: 'graph.html'
    title: 'graph page'
    chunks: ['chunk-vendors', 'chunk-common', 'graph']
  login:
    entry: './src/pages/login/login.js'
    template: 'public/login.html'
    filename: 'login.html'
    title: 'login page'
    chunks: ['chunk-vendors', 'chunk-common', 'login']

#项目基础配置
config:
  publicPath: '/'   #项目root 目录
  outputDir: './dist'  #构建文件输出目录
  lintOnSave: true  #是否在保存的时候检查
  assetsDir: 'static' #静态文件输出路径
  runtimeCompiler: false #是否使用包含运行时编译器的 Vue 构建版本
  parallel: true #是否为 Babel 或TypeScript 使用 thread-loader子进程去并发的执行压缩
  productionSourceMap: false #生产环境是否生成 sourceMap 文件，一般情况不建议打开
  pages: *pages #多页面配置
  css: *cssConfig  #css的配置
  devServer: *devServeConfig #热部署配置